### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by paulobocanegra** [jh177/tablelog#3]
Backend Routes

- [ X] Contains the following sections: HTML, API Endpoints(Backend)
- [ X] Each route has a description
- [ X] API Endpoint routes contains wildcard variables written in `snake_case`
- [ X] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [ ] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

Before checking out the last requirement for the backend routes I would like to ask you a question:  Are we planing to render all the reviews that one restaurant has? With that in mind, if we have a restaurant show page, and we do want to list all the reviews in this page, we may need a nested route for all the reviews for the given restaurant: 

       GET  /api/restaurants/:restaurant_id/reviews

This is only if we do plan on showing the reviews of each restaurant on their show page. Otherwise you will not need this.

Let me know what you think!

**Comment by jh177** [comment]
Thanks Paulo.
Yes, I do want to list all the reviews on the show page of the restaurant. I will add the nested reviews route to the restaurants routes.
